version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - tmp_data:/app/tmp
    restart: unless-stopped

volumes:
  tmp_data: 